### ISSUE TITLE
ibmcloud cdb isn't a valid command

### ISSUE THREAD

**Issue by pablohalamaj** [ibm-cloud-docs/databases-for-mongodb#2]
The document syas that to login into the mongodb we can use:

`$ ibmcloud cdb deployment-connections --start -u admin mongodb-production`

As with "ibmcloud version 1.0.0+908f90a-2020-03-30T06:37:22+00:00" ,` ibmcloud cdb` reponse:

FAILED
'cdb' is not a registered command. See 'ibmcloud help'.

**Comment by DailyAlice** [comment]
You have to install the plugin -- [docs here](https://cloud.ibm.com/docs/databases-cli-plugin?topic=cloud-databases-cli-cdb-reference) -- for the `cdb` command.
