### ISSUE TITLE
Clarification around the use of MongoDB Compass for MongoDB databases deployed as a private endpoints

### ISSUE THREAD

**Issue by ibmchas** [ibm-cloud-docs/databases-for-mongodb#3]
It is not clear in the current documentation if it is even possible for MongoDB Compass to connect to a private endpoint, the default deployment method of MongoDB is by public endpoint, however if you deploy it as private endpoint MongoDB Compass fail to connect :( 

Therefore I seek clarity around the following;

1. Is MongoDB Compass supported on for private endpoints - If so what is there any prereqs ? 
2. Is there a way of updating existing deployments from private to public (since the command below seems to fail)
3. If 1. & 2. is not supported then we should put a note in the documentation to guide the user of any limitations.

```
# ibmcloud resource service-instance-update MongoDB-5n --service-endpoints public
Error Code: RC-ServiceBrokerErrorResponse
Message: [400, Bad Request] We were unable to complete your request: deployment.enable_public_endpoints cannot be modified on this deployment, deployment.enable_private_endpoints cannot be modified on this deployment. Try again with valid values or contact support if the issue persists.
```
The following [support document](https://www.ibm.com/support/pages/how-can-you-connect-icd-mongodb-using-mongodb-compass) is also not specific on or how to connect Compass to private endpoints, I'm assuming it only reflect the default deployment.

**Comment by DailyAlice** [comment]
I don't know of anything that would prevent MongoDB Compass from working with Private Endpoints as long as it was running on a VM/container/system that was also in IBM Cloud. You may want to open a support ticket, as I am not very much help here.

Unfortunately, You are not able to change private endpoints to public endpoints on an existing MongoDB deployment.
